spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:file:./dev.db
    username: SA
    password:
    driverClassName=org: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081